const STATUS_TOKEN = {
  live: '--ok',
  completed: '--ok',
  active: '--ok',
  paid: '--ok',
  paid_out: '--ok',
  approved: '--ok',
  accepted: '--ok',
  verified: '--ok',
  released: '--ok',
  connected: '--ok',
  'in review': '--info',
  in_review: '--info',
  proof_submitted: '--info',
  processing: '--info',
  content_provided: '--info',
  'in progress': '--info',
  published: '--info',
  application_pending: '--info',
  requested: '--info',
  paused: '--warn',
  pending: '--warn',
  held: '--warn',
  awaiting: '--warn',
  draft: '--neutral',
  closed: '--neutral',
  cancelled: '--neutral',
  disputed: '--bad',
  rejected: '--bad',
  restricted: '--bad',
  suspended: '--bad',
};

const LABELS = {
  LIVE: 'Live',
  DRAFT: 'Draft',
  PAUSED: 'Paused',
  CLOSED: 'Closed',
  REQUESTED: 'Requested',
  APPLICATION_PENDING: 'Pending',
  ACCEPTED: 'Accepted',
  CONTENT_PROVIDED: 'Content provided',
  PUBLISHED: 'Published',
  PROOF_SUBMITTED: 'Proof submitted',
  IN_REVIEW: 'In review',
  VERIFIED: 'Verified',
  RELEASED: 'Released',
  PAID_OUT: 'Paid out',
  CANCELLED: 'Cancelled',
  DISPUTED: 'Disputed',
  PENDING: 'Pending',
  APPROVED: 'Approved',
  REJECTED: 'Rejected',
  ACTIVE: 'Active',
  SUSPENDED: 'Suspended',
  VERIFIED_PAGE: 'Verified',
};

export function getPillStyle(status) {
  const label = LABELS[status] || status?.replace(/_/g, ' ') || 'Unknown';
  const key = label.toLowerCase().replace(/_/g, ' ');
  const token = STATUS_TOKEN[key] || STATUS_TOKEN[status?.toLowerCase()] || '--neutral';
  return {
    label,
    style: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: 6,
      padding: '3px 9px 3px 8px',
      borderRadius: 7,
      fontSize: '11.5px',
      fontWeight: 700,
      background: `color-mix(in oklch, var(${token}) 13%, white)`,
      color: `var(${token})`,
      whiteSpace: 'nowrap',
    },
    dotColor: `var(${token})`,
  };
}
